### ISSUE TITLE
Compilation error: cannot import Phoenix.Endpoint.Cowboy2Adapter.info/3

### ISSUE THREAD

**Issue by neilberkman** [msaraiva/surface_app#1]
Following the instructions, I get the following on the `mix phx.server` step:

```
== Compilation error in file lib/phoenix/endpoint/cowboy_adapter.ex ==
** (CompileError) lib/phoenix/endpoint/cowboy_adapter.ex:78: cannot import Phoenix.Endpoint.Cowboy2Adapter.info/3 because it is undefined or private
    (elixir 1.10.3) src/elixir_import.erl:64: :elixir_import.calculate/6
    (elixir 1.10.3) src/elixir_import.erl:18: :elixir_import.import/4
could not compile dependency :phoenix, "mix compile" failed. You can recompile this dependency with "mix deps.compile phoenix", update it with "mix deps.update phoenix" or clean it with "mix deps.clean phoenix"
```

**Comment by msaraiva** [comment]
Hi @neilberkman!

I've just tried it now following the instructions and it worked just fine. I guess I'm gonna need more information. For instance, how does your `mix.lock` look like? Has it changed after running `mix deps.get`?

**Comment by neilberkman** [comment]
Hi @msaraiva -
`mix.lock` is unchanged after running `mix deps.get`:
https://gist.github.com/neilberkman/e39ce11404b08d609f0f30aa72d6cea9#file-gistfile1-txt

**Comment by msaraiva** [comment]
All versions of Phoenix, LV and Surface have been updated, I believe this should have been solved. Please let me know if it doesn't.
