### ISSUE TITLE
Sourcecode for http://surface-demo.msaraiva.io/

### ISSUE THREAD

**Issue by mxrguspxrt** [msaraiva/surface_app#2]
Hello!

I hope you are doing good!

Is source code for http://surface-demo.msaraiva.io project open and available? I think it would be really helpful, as it contains examples for TextInput etc also (in full application).

Best regards!

**Comment by msaraiva** [comment]
Hi @mxrguspxrt!

The source code will be available as soon. Until then, is there any particular example of `TextInput` (or any other) that you might be interested? I far as I remember, all examples have their source code alongside, if you find one that doesn't, please let me know.

**Comment by mxrguspxrt** [comment]
I had some issue that I got solved already. Thank you for the response and good lucky making this awesome libary! :)
